### ISSUE TITLE
Module not found: Can't resolve 'multicodec/src/base-table.json'

### ISSUE THREAD

**Issue by jeffscottward** [multiformats/js-cid#140] opened 2021-02-23 18:43 UTC
Only seeing .js in that lib
<img width="175" alt="Screen Shot 2021-02-23 at 1 42 54 PM" src="https://user-images.githubusercontent.com/1263486/108891710-09594680-75dd-11eb-9652-bcb830e64bd1.png">

**Comment by vmx** [comment] 2021-02-23 19:00
@jeffscottward There were issues in the past that should be fixed by now. Can you try to upgrade to the latest version of js-cid and see if the issue is still there?

**Comment by jeffscottward** [comment] 2021-02-23 19:01
ok i will ping the author - not my pkg

**Comment by yuhr** [comment] 2021-03-02 16:25
Seeing this error too. It's not present for me. Aliasing `multicodec/src/base-table.js` to "multicodec/src/generated-table.js" is not working.

<img width="211" alt="Screenshot 2021-03-03 at 1 17 41" src="https://user-images.githubusercontent.com/18474125/109678746-42398280-7bbe-11eb-907d-40865bba85da.png">

I'm using:
```
    "ipfs-core": "^0.5.2",
```

**Comment by vmx** [comment] 2021-03-02 17:21
@yuhr That should be fixed by now. If you update your dependencies (your package-lock.json, you should be good.

**Comment by yuhr** [comment] 2021-03-03 06:03
Thanks, I cleaned up everything and reinstalled then the error disappeared.

**Comment by aschmahmann** [comment] 2021-03-08 16:18
looks like this issue was resolved

**Closed by aschmahmann** 2021-03-08 16:18 UTC
